name: assignment_3

channels:
  - conda-forge
  - defaults

dependencies:
  - jupyterlab
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pre-commit
  - pandas
  - plotly
  - pip:
    - kaleido





