[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.0"]


[tool.setuptools_scm]
write_to = "src/assignment_5_a_group/_version.py"

[tool.pytask.ini_options]
paths = ["./src/assignment_5_a_group", "./paper"]
infer_latex_dependencies = true
